language: node_js
sudo: false
node_js:
  - "6"
  - "5"
  - "4"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  npm install -g npm@2.15.1
install:
  - npm install
  - npm install -g codecov
script:
  - npm run validate
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - codecov
